export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  CASES: '/cases',
  APPROVAL_HISTORY: '/approval-history',
  CASE_DETAIL: '/cases/:caseId',
  AI_RESULT: '/cases/:caseId/ai-result',
  AI_ANALYSIS: '/cases/:caseId/analysis',
  AI_REVIEW: '/cases/:caseId/review',
  SEVERITY: '/cases/:caseId/severity',
  SUPPORT: '/cases/:caseId/support',
  FINAL_APPROVAL: '/cases/:caseId/final-approval',
  CASE_REPORTS: '/cases/:caseId/reports',
  STATISTICS: '/statistics',
  MAP: '/map',
  REPORT_DETAIL: '/reports/:reportId',
};
