"""add external report id to cases

Revision ID: 971fc9d435fb
Revises: 4658349909c7
Create Date: 2026-07-24 14:38:42.964695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '971fc9d435fb'
down_revision: Union[str, Sequence[str], None] = '4658349909c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('external_report_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'cases', ['external_report_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cases', type_='unique')
    op.drop_column('cases', 'external_report_id')
    # ### end Alembic commands ###
