"""add damage_grade and calculation_basis to subsidies

Revision ID: ff30abb9ce2b
Revises: 73c16bb0c7f2
Create Date: 2026-07-30 17:04:33.265156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff30abb9ce2b'
down_revision: Union[str, Sequence[str], None] = '73c16bb0c7f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subsidies', sa.Column('damage_grade', sa.String(length=255), nullable=True))
    op.add_column('subsidies', sa.Column('calculation_basis', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subsidies', 'calculation_basis')
    op.drop_column('subsidies', 'damage_grade')
    # ### end Alembic commands ###
